### ISSUE TITLE
Too much nom!

### ISSUE THREAD

**Issue by kirkegaard** [leah/cookiecookiecookie#2]
You can continue to click the buttons even though the popup is fading out which makes it go NOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOMNOM :D

**Comment by leah** [comment]
Haha! I actually decided I didn't like the "nom" sounds so I just removed them. 😝
