### ISSUE TITLE
Non-JSON cookies can break your website

### ISSUE THREAD

**Issue by david-ma** [leah/cookiecookiecookie#3]
Bug report: Non-JSON cookies will break the code on page.tsx.

This issue probably won't affect anyone visiting your website directly, there shouldn't be any cookies you didn't set yourself.
But if you ever add Google Analytics, or if there are other cookies that make their way onto your domain, then it might break your website. So I think it's worth fixing this error.

I noticed this when trying to run your website on my website, which is a proxier, so it uses my own domain to run your scripts:
https://monetiseyourwebsite.com/proxy/https://www.cookiecookiecookie.com/
(I mirror your website & replace the images with paintings by Claude Monet)
I did my website as a learning/joke project & I use a cookie to try to reduce bot traffic.

See screenshot:
<img width="1400" alt="Screenshot 2024-04-02 at 1 18 49 pm" src="https://github.com/leah/cookiecookiecookie/assets/3320713/9610f48b-f564-4057-9a87-fc9747b73bd4">

Slightly related bug: things that read the "[initialCookies](https://github.com/leah/cookiecookiecookie/blob/main/app/page.tsx#L61)" array, expecting valid cookies, might break later on if a cookie IS parseable JSON but not a valid `type Cookie`.

Pull request incoming.

**Comment by leah** [comment]
Interesting and good bug catch. I didn't really think about anything else setting cookies.
